# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.
baseURL = "https://op-team.github.io/"
languageCode = "en-us"
title = "OP Team"
theme = "academic"